name: Android CI (no wrapper)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install SDKMAN! and Gradle 8.7
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle -v

      # بیلد هر دو وِریِنت — اگر یکی نداری، همون یکیش رو بزن
      - name: Build Buyer/Seller debug APKs
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle --no-daemon --stacktrace \
            assembleBuyerDebug assembleSellerDebug

      - name: Upload debug APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: |
            app/build/outputs/apk/**/debug/*.apk
          if-no-files-found: warn
