name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # بدون gradlew - خود Gradle روی رانر نصب می‌شود
      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      # اول سعی می‌کند buyer/seller را بسازد؛ اگر نبودند، فقط debug را می‌سازد
      - name: Build APKs
        run: |
          gradle -q :app:assembleBuyerDebug :app:assembleSellerDebug || gradle -q :app:assembleDebug

      - name: Upload Buyer APK (if exists)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: buyer-apk
          path: app/build/outputs/apk/buyer/debug/*.apk
          if-no-files-found: ignore

      - name: Upload Seller APK (if exists)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: seller-apk
          path: app/build/outputs/apk/seller/debug/*.apk
          if-no-files-found: ignore

      - name: Upload Debug APK (fallback)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
