name: Android CI (module :app, no wrapper)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # نصب پکیج‌های لازم SDK (پلتفرم و بیلد تولز)
      - name: Install Android SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # اجرای گرادل بدون نیاز به gradlew (خودِ اکشن Gradle 8.7 را دانلود و کش می‌کند)
      - name: Assemble Debug APK (module :app)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: :app:assembleDebug --stacktrace --no-daemon

      # آپلود خروجی APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
