name: Android CI (soma.app.foad)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # نصب Gradle بدون استفاده از کش و بدون gradlew (wrapper)
      - name: Set up Gradle (no wrapper, no cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-disabled: true

      - name: Build Buyer/Seller APKs
        run: |
          gradle --version
          gradle assembleBuyerDebug assembleSellerDebug

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soma-apks
          path: |
            app/build/outputs/apk/buyer/debug/*.apk
            app/build/outputs/apk/seller/debug/*.apk
