name: Android CI (soma.app.foad)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle (no wrapper, no cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-disabled: true

      # بیلد با خروجی ساده و کامل تا خطا گم نشود
      - name: Build Buyer/Seller APKs (verbose)
        run: |
          set -o pipefail
          gradle assembleBuyerDebug assembleSellerDebug \
            --console=plain --info --stacktrace --warning-mode all --no-daemon \
            | tee gradle-build.log

      # استخراج خطوط کلیدی خطا از لاگ
      - name: Show key errors (Kotlin/AAPT/FAILURE)
        if: failure()
        run: |
          echo "================ FAILURES ================="
          grep -n "FAILURE: Build failed with an exception" -n gradle-build.log || true
          echo "================ Kotlin 'e:' lines ======="
          grep -n "^e: " gradle-build.log | tail -n 50 || true
          echo "============= Android resource linking ===="
          grep -n "Android resource linking failed" gradle-build.log -n || true
          echo "================ Duplicate class =========="
          grep -n "Duplicate class " gradle-build.log || true
          echo "================ ERROR TAIL ==============="
          tail -n 400 gradle-build.log
          echo "=========================================="

      - name: Upload APK artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: soma-apks
          path: |
            app/build/outputs/apk/buyer/debug/*.apk
            app/build/outputs/apk/seller/debug/*.apk

      - name: Upload Gradle logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: gradle-build.log
