name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # از خود گریدل استفاده می‌کنیم (بدون gradlew)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Build Buyer/Seller APKs
        run: |
          gradle --version
          gradle :app:assembleBuyerDebug :app:assembleSellerDebug --stacktrace

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: |
            app/build/outputs/apk/buyer/debug/*.apk
            app/build/outputs/apk/seller/debug/*.apk
          if-no-files-found: warn
