name: Android CI (soma.app.foad)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Buyer/Seller APKs
        run: ./gradlew assembleBuyerDebug assembleSellerDebug

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soma-apks
          path: |
            app/build/outputs/apk/buyer/debug/*.apk
            app/build/outputs/apk/seller/debug/*.apk
